name: Bug Report
description: Create a report to help us improve OpenList Desktop
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu
        - Other Linux Distribution
        - Other
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: System Architecture
      description: What system architecture are you using?
      options:
        - x64 (64-bit)
        - arm64
        - x86 (32-bit)
        - Other
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: OpenList Desktop Version
      description: What version of OpenList Desktop are you using?
      placeholder: e.g. v0.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Application Logs
      description: Please provide relevant logs from the Logs tab in the application
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all required environment information
          required: true
        - label: I can reproduce this issue consistently
          required: true
