blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/OpenListTeam/openlist-desktop/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/OpenListTeam/openlist-desktop/blob/main/README.md
    about: Read the project documentation and setup guides
  - name: 🔧 OpenList Documentation
    url: https://docs.oplist.org/
    about: Official OpenList documentation for the underlying service
  - name: 🌐 Rclone Documentation
    url: https://rclone.org/docs/
    about: Official Rclone documentation for remote storage configuration
