name: Feature Request
description: Suggest an idea for OpenList Desktop
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added.
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what problem this feature would solve.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of the application does this feature relate to?
      options:
        - User Interface / UX
        - OpenList Service Management
        - Rclone / Remote Storage
        - Settings / Configuration
        - Logging / Monitoring
        - Performance / Optimization
        - Security / Authentication
        - Cross-platform Support
        - Auto-updater
        - Other
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Check all that apply
      options:
        - label: I am willing to help implement this feature
        - label: This feature requires changes to the frontend (Vue.js)
        - label: This feature requires changes to the backend (Rust/Tauri)
        - label: This feature requires changes to external binaries (OpenList/Rclone)
        - label: This feature affects multiple platforms

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: This feature request is specific to OpenList Desktop (not the underlying OpenList or Rclone projects)
          required: true
