name: Question or General Issue
description: Ask a question or report an issue that doesn't fit other categories
title: '[QUESTION] '
labels: ['question', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Have a question or issue that doesn't fit the other categories? Please provide details below.

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of question or issue is this?
      options:
        - General usage question
        - Configuration question
        - Compatibility question
        - Best practices question
        - Troubleshooting help
        - Unclear behavior
        - Integration question
        - Development question
        - Other
    validations:
      required: true

  - type: textarea
    id: question-description
    attributes:
      label: Question or Issue Description
      description: Describe your question or issue in detail.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context that might help us understand your question.
      placeholder: |
        - What are you trying to accomplish?
        - What have you already tried?
        - What resources have you consulted?

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Ubuntu
        - Other Linux Distribution
        - Other
        - Not applicable

  - type: input
    id: app-version
    attributes:
      label: OpenList Desktop Version
      description: What version of OpenList Desktop are you using? (if applicable)
      placeholder: e.g. v0.1.0

  - type: textarea
    id: configuration-details
    attributes:
      label: Configuration Details
      description: If relevant, describe your current configuration.
      placeholder: |
        - Service settings
        - Mount configurations
        - Custom binary paths
        - Special flags or options

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen? (if applicable)

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened? (if applicable)

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have checked the documentation and README
          required: true
        - label: This question is specifically about OpenList Desktop (not general OpenList or Rclone questions)
          required: true
